### ISSUE TITLE
test/p6est_test_all fails on 32-bit architectures

### ISSUE THREAD

**Issue by ginggs** [cburstedde/p4est#63]
**test/p6est_test_all** fails on 32-bit architectures, all other tests are successful.
Is it possible for this test to be adapted to succeed on 32-bit?
```
...
[p4est] Into p6est_ghost_new
[p4est]  Into p4est_ghost_new FACE
[p4est]  Done p4est_ghost_new
[p4est] Done p6est_ghost_new
[p4est] Into p6est_ghost_new
[p4est]  Into p4est_ghost_new CORNER
[p4est]  Done p4est_ghost_new
[p4est] Done p6est_ghost_new
[p4est] Into p6est_ghost_expand
[p4est]  Into p4est_ghost_expand CORNER
[p4est]  Done p4est_ghost_expand
[p4est] Done p6est_ghost_expand
[p4est] Into p6est_ghost_expand
[p4est]  Into p4est_ghost_expand CORNER
[p4est]  Done p4est_ghost_expand
[p4est] Done p6est_ghost_expand
[p4est] Into p6est_balance with 1497 total layers in 313 total columns
[p4est]  Into p4est_balance FACE with 313 total quadrants
[p4est]  Done p4est_balance with 385 total quadrants
[p4est]  Into p4est_ghost_new CORNER
[p4est]  Done p4est_ghost_new
[p4est]  Into p4est_lnodes_new, degree 2
[p4est]  Done p4est_lnodes_new with 1559 global nodes
[libsc 0] Abort: Returned NULL from malloc
[libsc 0] Abort: src/sc.c:377
[libsc 0] Abort: Obtained 0 stack frames
```

**Comment by cburstedde** [comment]
If malloc returns NULL, we are out of memory. This seems strange with a relatively small mesh. You might call some of  the *_memory_used functions to investigate the memory consumption of the p4est data structures in the test and relate it to the memory on your machine/architecture.

**Comment by tamiko** [comment]
@cburstedde We are currently debugging this issue.

First of all we observe that `p6est_test_all`:
 - shows a large builtup of used virtual and physical memory (we are talking about more than 1GiB VIRT and RES)
 - intermittent hangs and intermittent segfaults.

When we trigger the assert in question it is certainly due to an exhaustion of available virtual memory space.

In order to investigate further I have added a small debug output to `src/sc.c` to print out the actual memory request:
```
diff --git a/src/sc.c b/src/sc.c
index 63d47bc7..bb83cdf3 100644
--- a/src/sc.c
+++ b/src/sc.c
@@ -374,6 +374,9 @@ sc_malloc_aligned (size_t alignment, size_t size)
     char               *ptr;
     ptrdiff_t           shift, modu;
 
+    if(alloc_ptr == NULL) {
+      printf ("ALLOC: %x, %x, %x, %x\n", size, extrasize, signalign, alloc_size);
+    }
     SC_CHECK_ABORT (alloc_ptr != NULL, "Returned NULL from malloc");
 
     /* compute shift to the right where we put the actual data */
```

I then get something like

```
[p4est]  Into p4est_balance FACE with 313 total quadrants
[p4est]  Done p4est_balance with 385 total quadrants
[p4est]  Into p4est_ghost_new CORNER
[p4est]  Done p4est_ghost_new
[p4est]  Into p4est_lnodes_new, degree 2
[p4est]  Done p4est_lnodes_new with 1559 global nodes
ALLOC: a4acd2b8, 8, 4, a4acd2c4
[libsc 0] Abort: Returned NULL from malloc
[libsc 0] Abort: src/sc.c:380
[libsc 0] Abort: Obtained 14 stack frames
[libsc 0] Stack 0: libsc-2.2.39-7089.so(+0xa4a0) [0xf7e804a0]
[libsc 0] Stack 1: libsc-2.2.39-7089.so(sc_abort+0x15) [0xf7e7f6f5]
[libsc 0] Stack 2: libsc-2.2.39-7089.so(+0x9be4) [0xf7e7fbe4]
[libsc 0] Stack 3: libsc-2.2.39-7089.so(+0xa0bf) [0xf7e800bf]
[libsc 0] Stack 4: libsc-2.2.39-7089.so(sc_malloc+0x31) [0xf7e800f1]
[libsc 0] Stack 5: libsc-2.2.39-7089.so(sc_array_init_count+0x35) [0xf7e81cf5]
[libsc 0] Stack 6: libsc-2.2.39-7089.so(sc_array_new_count+0x32) [0xf7e81d32]
[libsc 0] Stack 7: libp4est-2.2.196-ea25.so(+0x84f78) [0xf7f31f78]
[libsc 0] Stack 8: libp4est-2.2.196-ea25.so(p6est_profile_balance_local+0x272) [0xf7f33802]
[libsc 0] Stack 9: libp4est-2.2.196-ea25.so(p6est_balance_ext+0x12c) [0xf7f2f65c]
[libsc 0] Stack 10: libp4est-2.2.196-ea25.so(p6est_balance+0x26) [0xf7f2f806]
[libsc 0] Stack 11: p6est_test_all(+0x1a2e) [0x56642a2e]
[libsc 0] Stack 12: libc.so.6(__libc_start_main+0x106) [0xf744bf76]
[libsc 0] Stack 13: p6est_test_all(+0x1ff1) [0x56642ff1]
```

The alloc is interesting: `0xa4acd2b8` is 2.6GiB - an amount of virtual memory that cannot be allocated on 32 bit linux platforms (the userland/kernel virt memory split is typically 2GiB).

Would you mind advising how to debug further?

**Comment by tamiko** [comment]
For convenience here is a backtrace of the abort:
```
#0  0xf7fcf549 in __kernel_vsyscall ()
#1  0xf74c0be6 in raise () from /lib/libc.so.6
#2  0xf74a930c in abort () from /lib/libc.so.6
#3  0xf7ede225 in sc_MPI_Abort (comm=1140850688, exitcode=1) at src/sc_mpi.c:84
#4  0xf7edf594 in sc_abort_handler () at src/sc.c:959
#5  0xf7ede6f5 in sc_abort () at src/sc.c:912
#6  0xf7edebe4 in sc_abort_verbose (filename=0xf7efa013 "src/sc.c", lineno=380, msg=0xf7efa0fa "Returned NULL from malloc") at src/sc.c:969
#7  0xf7edf0bf in sc_malloc_aligned (size=size@entry=2125763484, alignment=4) at src/sc.c:380
#8  0xf7edf0f1 in sc_malloc (package=0, size=2125763484) at src/sc.c:527
#9  0xf7ee0cf5 in sc_array_init_count (array=0x5656fec8, elem_size=4, elem_count=531440871) at src/sc_containers.c:130
#10 0xf7ee0d32 in sc_array_new_count (elem_size=4, elem_count=531440871) at src/sc_containers.c:57
#11 0xf7f90f78 in p6est_profile_compress (profile=profile@entry=0x56564868) at src/p6est_profile.c:491
#12 0xf7f92802 in p6est_profile_balance_local (profile=0x56564868) at src/p6est_profile.c:870
#13 0xf7f8e65c in p6est_balance_ext (p6est=0x5655f758, btype=P8EST_CONNECT_FACE, max_diff=<optimized out>, min_diff=<optimized out>, init_fn=0x56557200 <init_fn>, replace_fn=0x0)
    at src/p6est.c:2554
#14 0xf7f8e806 in p6est_balance (p6est=0x5655f758, btype=P8EST_CONNECT_FACE, init_fn=0x56557200 <init_fn>) at src/p6est.c:2577
#15 0x56556a2e in main (argc=<optimized out>, argv=<optimized out>) at test/test_all6.c:315
```

**Comment by cburstedde** [comment]
Thanks for checking and verifying that all other tetst are ok.

So the allocation is for 2.8G, understandable it crashes on 32bit. I'm not sure why we enter profiling inside balance there.

About p6est tests @tisaac might know more.

**Comment by cburstedde** [comment]
#296 reduces the refinement level by 1. Does this suffice to bring down memory usage?

**Comment by tamiko** [comment]
@cburstedde Checking!

**Comment by cburstedde** [comment]
Thanks for checking. Can I assume the problem has gone away?

**Comment by tamiko** [comment]
@cburstedde Yes, please close.
